### ISSUE TITLE
Calculated calories in UI

### ISSUE THREAD

**Issue by VitalyVaryvdin** [simonoppowa/OpenNutriTracker#28]
Congrats on the release. Been following for a while

Got a few issues regarding calories calculation

1. Seems like I'm not able to change any calculation/macros goal in the settings?
2. Calories shown after on-boarding (maintenance calories) are different with what's displayed on main screen (calories calculated per goal). Not sure if that's intended, but it's quite confusing
3. It would be awesome seeing different calculated calories somewhere (probably by clicking calories goal on main screen?) the way it is implemented here https://tdeecalculator.net/. Knowing BMR and maintenance calories is helpful sometimes.
4. What is the strategy used to calculate cutting calories? Both of my maintenance and cutting calculated calories are different comparing to tdeecalculator.net. I'm aware that they utilize different equation, but difference if quite huge - around 500kkcal 

upd:

> 4. What is the strategy used to calculate cutting calories? Both of my maintenance and cutting calculated calories are different comparing to tdeecalculator.net. I'm aware that they utilize different equation, but difference if quite huge - around 500kkcal 

Found out in the code. -500 or +500 of calculated TDEE.

upd:

Diary also shows my maintenance calories instead of cutting calories

**Comment by simonoppowa** [comment]
Hey Vitaly,

1. Customizing calorie and macro goals is currently not possible. I will try to add more customization features in future updates. I just want to make sure that nobody is harmed by setting wrong goals on accident.
2. The wrong calorie and macro texts were a bug in the onboarding and diary screen. I changed it now and it will be fixed in the next update. Thanks for reporting 🙂
3. Good feature request. I will think about implementing that.
4. It's indeed -500 calories. This is the suggested amount by the WHO.

**Comment by VitalyVaryvdin** [comment]
Hey Simon,
Thanks a lot :)
Looking forward to future work on the project

Closing now as commits fixing the only issue reported here were pushed :)
